server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: on_param
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local

---
## LOCAL PROP
server:
  port: 8080

spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properies:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    username: url
    password: 1234

prop:
  service:
    domain: http://localhost:${server.port}/
    url:
      domain: ${prop.service.domain}url/